Feature/ex 1
felipeabdo/orion-bootcamp pull request #2
Opened 2023-10-12 02:45 UTC by felipeabdo

2023-10-12 02:47 UTC, felipeabdo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 1](https://trello.com/c/ExukaF9M/144-exerc%C3%ADcio-1)

2023-10-13 19:41 UTC, matheus-yudi-newrizon requested changes

2023-10-13 19:41 UTC, matheus-yudi-newrizon commented on src/ex-1.ts
> +function contarVogais(palavra: string): number {
É uma boa prática sempre documentar o nosso código, facilita o entendimento e a manutenção.

Sugestão de doc oficial: modelo de documentação do TSDoc (https://tsdoc.org/)

2023-10-13 19:41 UTC, matheus-yudi-newrizon commented on dist/ex-1.js
Não precisa commitar os arquivos dist/ e o node_modules.

2023-10-13 19:41 UTC, matheus-yudi-newrizon commented on src/ex-1.ts
> +  let contar = 0;
Não faria mais sentido nomear como "contagem" ou "quantidade" por exemplo?

2023-10-13 19:41 UTC, matheus-yudi-newrizon commented on src/ex-1.ts
> +  const resultadoElement = document.querySelector("p");
É bom deixar o nosso código o mais legível sempre que possível. Para isso, é uma boa adicionar espaços entre as declarações e agrupar as variáveis/execuções, colocar comentários relevantes e remover espaços no início/fim do método.

2023-10-13 19:41 UTC, matheus-yudi-newrizon commented on src/ex-1.ts
> +  if (resultadoElement) {
Também é uma boa prática não mesclar idiomas na declaração de variáveis, métodos e tipos.

Seguindo o padrão do restante do código, ficaria melhor nomear essa variável como **resultadoElemento** ou então "paragrafoResultado".

2023-10-13 19:41 UTC, matheus-yudi-newrizon commented on src/ex-1.ts
> +  const vogais = "aeiouAEIOUáàéíóúãõâêôäëïöü";
Para não precisar mapear todas as vogais e suas variantes (maiúscula/minúscula), você poderia transformar a palavra toda para lowercase ou uppercase.

2023-10-13 19:41 UTC, matheus-yudi-newrizon commented on src/ex-1.ts
> +console.log(contarVogais('Felipe'))
Poderia colocar uma mensagem mais clara no momento do console para que seja possível visualizar no inspetor, ou então alterar para um alert()

2023-10-14 00:46 UTC, matheus-yudi-newrizon approved these changes

2023-10-14 00:46 UTC, merged