Feature/ex 2
felipeabdo/orion-bootcamp pull request #3
Opened 2023-10-13 12:17 UTC by felipeabdo

Esercício 2 com as demonstrações pedidas.

2023-10-13 12:24 UTC, felipeabdo commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Felipe Abdo] Exercício 2](https://trello.com/c/eo1GEBah/158-felipe-abdo-exerc%C3%ADcio-2)

2023-10-13 21:05 UTC, dairsposito requested changes
Considerar também os apontamentos feitos no PR do exercício 1 neste exercício também!

2023-10-13 21:05 UTC, dairsposito commented on exercício-2/src/index.ts
> +function getBioByIdFuncional(id: number): string | null {
O ideal é que seja informado a lista nos parâmetros da função, pois a função não pode acessar/alterar dados externos.

2023-10-13 21:05 UTC, dairsposito commented on exercício-2/src/index.ts
> +  return person ? person.bio : null;
Dica: aqui você pode retornar da seguinte forma `return person?.bio;`

2023-10-13 21:05 UTC, dairsposito commented on exercício-2/src/index.ts
> +function getNameByIdFuncional(id: number): string | null {
Considerar os mesmos quesitos da função anterior

2023-10-13 21:05 UTC, dairsposito commented on exercício-2/src/index.ts
> +function deleteItemByIdFuncional(id: number): void {
Como no paradigma funcional não pode alterar o dado original, você deve informar a lista e o id que deseja remover, retornando assim uma nova lista sem o id em questão. Desta forma você não altera e nem acessa dados externos à função.

2023-10-13 21:05 UTC, dairsposito commented on exercício-2/src/index.ts
> +function updateNameAndBioByIdFuncional(id: number, newName: string | null, newBio: string | null): void {
Considerar o comentário da função anterior.

2023-10-13 21:05 UTC, dairsposito commented on exercício-2/src/index.ts
> +      if (newName !== null) {
Se a pessoa passar 0 como nome? Ou undefined? O ideal é apenas comparar usando a própria variável. `if (newName)`
Desta forma, se a pessoa informar 0, string vazia, false ou nulo, ele vai validar.

2023-10-13 21:05 UTC, dairsposito commented on exercício-2/src/index.ts
> +        item.bio = newBio;
Além da consideração na condição anterior, você pode usar um ternário também `item.bio = newBio ?? item.bio`

2023-10-13 21:05 UTC, dairsposito commented on exercício-2/src/index.ts
> +      if (newName !== null) {
Considerar mesmo apontamento do paradigma funcional para realizar a condicional.

2023-10-14 02:04 UTC, dairsposito requested changes
Remover arquivo do github desktop

2023-10-14 02:04 UTC, dairsposito commented on exercício-2/GitHubDesktop-linux-3.1.1-linux1.deb
Remover este arquivo!

2023-10-14 02:40 UTC, dairsposito requested changes
Remover o arquivo github desktop do versionamento.

2023-10-14 02:40 UTC, dairsposito commented on exercício-2/GitHubDesktop-linux-3.1.1-linux1.deb
Remover esse arquivo do versionamento!

2023-10-14 12:06 UTC, dairsposito approved these changes

2023-10-14 12:06 UTC, merged